export const EVENTS = {
    RATE_LIMIT: 'rateLimit',
    READY: 'ready',
    RESUME: 'resume',
    GUILD_CREATE: 'guildCreate',
    GUILD_DELETE: 'guildDelete',
    GUILD_UPDATE: 'guildUpdate',
    GUILD_UNAVAILABLE: 'guildUnavailable',
    GUILD_AVAILABLE: 'guildAvailable',
    GUILD_MEMBER_ADD: 'guildMemberAdd',
    GUILD_MEMBER_REMOVE: 'guildMemberRemove',
    GUILD_MEMBER_UPDATE: 'guildMemberUpdate',
    GUILD_MEMBER_AVAILABLE: 'guildMemberAvailable',
    GUILD_MEMBER_SPEAKING: 'guildMemberSpeaking',
    GUILD_MEMBERS_CHUNK: 'guildMembersChunk',
    GUILD_INTEGRATIONS_UPDATE: 'guildIntegrationsUpdate',
    GUILD_ROLE_CREATE: 'roleCreate',
    GUILD_ROLE_DELETE: 'roleDelete',
    GUILD_ROLE_UPDATE: 'roleUpdate',
    GUILD_EMOJI_CREATE: 'emojiCreate',
    GUILD_EMOJI_DELETE: 'emojiDelete',
    GUILD_EMOJI_UPDATE: 'emojiUpdate',
    GUILD_BAN_ADD: 'guildBanAdd',
    GUILD_BAN_REMOVE: 'guildBanRemove',
    CHANNEL_CREATE: 'channelCreate',
    CHANNEL_DELETE: 'channelDelete',
    CHANNEL_UPDATE: 'channelUpdate',
    CHANNEL_PINS_UPDATE: 'channelPinsUpdate',
    MESSAGE_CREATE: 'message',
    MESSAGE_DELETE: 'messageDelete',
    MESSAGE_UPDATE: 'messageUpdate',
    MESSAGE_BULK_DELETE: 'messageDeleteBulk',
    MESSAGE_REACTION_ADD: 'messageReactionAdd',
    MESSAGE_REACTION_REMOVE: 'messageReactionRemove',
    MESSAGE_REACTION_REMOVE_ALL: 'messageReactionRemoveAll',
    USER_UPDATE: 'userUpdate',
    USER_NOTE_UPDATE: 'userNoteUpdate',
    USER_SETTINGS_UPDATE: 'clientUserSettingsUpdate',
    USER_GUILD_SETTINGS_UPDATE: 'clientUserGuildSettingsUpdate',
    PRESENCE_UPDATE: 'presenceUpdate',
    VOICE_STATE_UPDATE: 'voiceStateUpdate',
    TYPING_START: 'typingStart',
    TYPING_STOP: 'typingStop',
    WEBHOOKS_UPDATE: 'webhookUpdate',
    DISCONNECT: 'disconnect',
    RECONNECTING: 'reconnecting',
    ERROR: 'error',
    WARN: 'warn',
    DEBUG: 'debug',
};

export const DISCORD_DJS_PERMISSIONS = {
    CREATE_INSTANT_INVITE: 'createInstantInvite',
    KICK_MEMBERS: 'kickMembers',
    BAN_MEMBERS: 'banMembers',
    ADMINISTRATOR: 'administrator',
    MANAGE_CHANNELS: 'manageChannels',
    MANAGE_GUILD: 'manageGuild',
    ADD_REACTIONS: 'addReactions',
    VIEW_AUDIT_LOG: 'viewAuditLog',
    VIEW_CHANNEL: 'readMessages',
    SEND_MESSAGES: 'sendMessages',
    SEND_TTS_MESSAGES: 'sendTTSMessages',
    MANAGE_MESSAGES: 'manageMessages',
    EMBED_LINKS: 'embedLinks',
    ATTACH_FILES: 'attachFiles',
    READ_MESSAGE_HISTORY: 'readMessageHistory',
    MENTION_EVERYONE: 'mentionEveryone',
    USE_EXTERNAL_EMOJIS: 'externalEmojis',
    CONNECT: 'voiceConnect',
    SPEAK: 'voiceSpeak',
    MUTE_MEMBERS: 'voiceMuteMembers',
    DEAFEN_MEMBERS: 'voiceDeafenMembers',
    MOVE_MEMBERS: 'voiceMoveMembers',
    USE_VAD: 'voiceUseVAD',
    PRIORITY_SPEAKER: 'voicePrioritySpeaker',
    CHANGE_NICKNAME: 'changeNickname',
    MANAGE_NICKNAMES: 'manageNicknames',
    MANAGE_ROLES: 'manageRoles',
    MANAGE_WEBHOOKS: 'manageWebhooks',
    MANAGE_EMOJIS: 'manageEmojis',
};

export const PERMISSIONS = [
    'createInstantInvite',
    'kickMembers',
    'banMembers',
    'administrator',
    'manageChannels',
    'manageGuild',
    'addReactions',
    'readMessages',
    'sendMessages',
    'sendTTSMessages',
    'manageMessages',
    'embedLinks',
    'attachFiles',
    'readMessageHistory',
    'mentionEveryone',
    'externalEmojis',
    'voiceConnect',
    'voiceSpeak',
    'voiceMuteMembers',
    'voiceDeafenMembers',
    'voiceMoveMembers',
    'voiceUseVAD',
    'changeNickname',
    'manageNicknames',
    'manageRoles',
    'manageWebhooks',
    'manageEmojis',
];

export const PERMISSIONS_NAMES = {
    createInstantInvite: 'Create Instant Invite',
    kickMembers: 'Kick Members',
    banMembers: 'Ban Members',
    administrator: 'Administrator',
    manageChannels: 'Manage Channels',
    manageGuild: 'Manage Guild',
    addReactions: 'Add Reactions',
    readMessages: 'Read Messages',
    sendMessages: 'Send Messages',
    sendTTSMessages: 'Send TTS Messages',
    manageMessages: 'Manage Messages',
    embedLinks: 'Embed Links',
    attachFiles: 'Attach Files',
    readMessageHistory: 'Read Message History',
    mentionEveryone: 'Mention Everyone',
    externalEmojis: 'External Emojis',
    voiceConnect: 'Voice Connect',
    voiceSpeak: 'Voice Speak',
    voiceMuteMembers: 'Voice Mute Members',
    voiceDeafenMembers: 'Voice Deafen Members',
    voiceMoveMembers: 'Voice Move Members',
    voiceUseVAD: 'Voice Use VAD',
    changeNickname: 'Change Nickname',
    manageNicknames: 'Manage Nicknames',
    manageRoles: 'Manage Roles',
    manageWebhooks: 'Manage Webhooks',
    manageEmojis: 'Manage Emojis',
};

export default {
    EVENTS,
    DISCORD_DJS_PERMISSIONS,
    PERMISSIONS,
    PERMISSIONS_NAMES,
};
