export const PERMISSIONS = [
    'createInstantInvite',
    'kickMembers',
    'banMembers',
    'administrator',
    'manageChannels',
    'manageGuild',
    'addReactions',
    'readMessages',
    'sendMessages',
    'sendTTSMessages',
    'manageMessages',
    'embedLinks',
    'attachFiles',
    'readMessageHistory',
    'mentionEveryone',
    'externalEmojis',
    'voiceConnect',
    'voiceSpeak',
    'voiceMuteMembers',
    'voiceDeafenMembers',
    'voiceMoveMembers',
    'voiceUseVAD',
    'changeNickname',
    'manageNicknames',
    'manageRoles',
    'manageWebhooks',
    'manageEmojis',
];

export const PERMISSIONS_NAMES = {
    createInstantInvite: 'Create Instant Invite',
    kickMembers: 'Kick Members',
    banMembers: 'Ban Members',
    administrator: 'Administrator',
    manageChannels: 'Manage Channels',
    manageGuild: 'Manage Guild',
    addReactions: 'Add Reactions',
    readMessages: 'Read Messages',
    sendMessages: 'Send Messages',
    sendTTSMessages: 'Send TTS Messages',
    manageMessages: 'Manage Messages',
    embedLinks: 'Embed Links',
    attachFiles: 'Attach Files',
    readMessageHistory: 'Read Message History',
    mentionEveryone: 'Mention Everyone',
    externalEmojis: 'External Emojis',
    voiceConnect: 'Voice Connect',
    voiceSpeak: 'Voice Speak',
    voiceMuteMembers: 'Voice Mute Members',
    voiceDeafenMembers: 'Voice Deafen Members',
    voiceMoveMembers: 'Voice Move Members',
    voiceUseVAD: 'Voice Use VAD',
    changeNickname: 'Change Nickname',
    manageNicknames: 'Manage Nicknames',
    manageRoles: 'Manage Roles',
    manageWebhooks: 'Manage Webhooks',
    manageEmojis: 'Manage Emojis',
};

export const PERMISSIONS_NUMBERS = {
    createInstantInvite: 1,
    kickMembers: 2,
    banMembers: 4,
    administrator: 8,
    manageChannels: 16,
    manageGuild: 32,
    addReactions: 64,
    viewAuditLogs: 128,
    voicePrioritySpeaker: 256,
    readMessages: 1024,
    sendMessages: 2048,
    sendTTSMessages: 4096,
    manageMessages: 8192,
    embedLinks: 16384,
    attachFiles: 32768,
    readMessageHistory: 65536,
    mentionEveryone: 131072,
    externalEmojis: 262144,
    voiceConnect: 1048576,
    voiceSpeak: 2097152,
    voiceMuteMembers: 4194304,
    voiceDeafenMembers: 8388608,
    voiceMoveMembers: 16777216,
    voiceUseVAD: 33554432,
    changeNickname: 67108864,
    manageNicknames: 134217728,
    manageRoles: 268435456,
    manageWebhooks: 536870912,
    manageEmojis: 1073741824,
    all: 2146958847,
    allGuild: 2080374975,
    allText: 805829713,
    allVoice: 871366929,
};

export const EMBED_LIMITS = {
    LIMIT_CONTENT: 2000,
    LIMIT_TOTAL_EMBED: 6000,
    LIMIT_TITLE: 256,
    LIMIT_DESCRIPTION: 2048,
    NUMBER_FIELDS: 25,
    LIMIT_FIELD_NAME: 256,
    LIMIT_FIELD_VALUE: 1024,
    LIMIT_FOOTER_TEXT: 2048,
    LIMIT_AUTHOR_NAME: 256,
};

export const CHANNEL_TYPES = {
    GUILD_TEXT: 0,
    DM: 1,
    GUILD_VOICE: 2,
    GROUP_DM: 3,
    GUILD_CATEGORY: 4,
    GUILD_NEWS: 5,
    GUILD_STORE: 6,
};

export const MESSAGE_TYPES = {
    DEFAULT: 0,
    RECIPIENT_ADD: 1,
    RECIPIENT_REMOVE: 2,
    CALL: 3,
    CHANNEL_NAME_CHANGE: 4,
    CHANNEL_ICON_CHANGE: 5,
    CHANNEL_PINNED_MESSAGE: 6,
    GUILD_MEMBER_JOIN: 7,
    USER_PREMIUM_GUILD_SUBSCRIPTION: 8,
    USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_1: 9,
    USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_2: 10,
    USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_3: 11,
};

export const CLIENT_STATUS_TYPES = {
    PLAYING: 0,
    STREAMING: 1,
    LISTENING: 2,
    WATCHING: 3,
};

export default {
    PERMISSIONS,
    PERMISSIONS_NAMES,
    PERMISSIONS_NUMBERS,
    EMBED_LIMITS,
    CHANNEL_TYPES,
    MESSAGE_TYPES,
    CLIENT_STATUS_TYPES,
};
