
export declare const AxonEnums: {
    HTTP_CODE: HTTP_CODE;
    HTTP_MESSAGES: HttpMessages;
    LIBRARY_TYPES: LIBRARY_TYPES;
    LOGGER_TYPES: LOGGER_TYPES;
    DB_TYPES: DB_TYPES;
    COMMAND_EXECUTION_TYPES: COMMAND_EXECUTION_TYPES;
    COMMAND_EXECUTION_STATE: COMMAND_EXECUTION_STATE;
    AXON_PERMISSION_LEVELS: AXON_PERMISSION_LEVELS;
    PERMISSION_ADMIN: 'ADMINISTRATOR';
    PERMISSION_MANAGER: 'MANAGE_GUILD';
    WEBHOOK_TYPES: WEBHOOK_TYPES;
    LOG_LEVELS: LOG_LEVELS;
    WEBHOOK_TO_COLOR: WEBHOOK_TO_COLOR;
    TYPE_ERRORS: TYPE_ERRORS;
};
