
export declare const DiscordEnums: {
        DISCORD_GATEWAY_EVENTS: DISCORD_GATEWAY_EVENTS;
        DISCORD_PERMISSIONS: DISCORD_PERMISSIONS;
        PERMISSION_NUMBERS: PERMISSIONS_NUMBERS;
        EMBED_LIMITS: EMBED_LIMITS;
        CHANNEL_TYPES: CHANNEL_TYPES;
        MESSAGE_TYPES: MESSAGE_TYPES;
        CLIENT_STATUS_TYPES: CLIENT_STATUS_TYPES;
};
