const permissions = [
    'createInstantInvite',
    'kickMembers',
    'banMembers',
    'administrator',
    'manageChannels',
    'manageGuild',
    'addReactions',
    'readMessages',
    'sendMessages',
    'sendTTSMessages',
    'manageMessages',
    'embedLinks',
    'attachFiles',
    'readMessageHistory',
    'mentionEveryone',
    'externalEmojis',
    'voiceConnect',
    'voiceSpeak',
    'voiceMuteMembers',
    'voiceDeafenMembers',
    'voiceMoveMembers',
    'voiceUseVAD',
    'changeNickname',
    'manageNicknames',
    'manageRoles',
    'manageWebhooks',
    'manageEmojis',
];

const permissionsNames = {
    createInstantInvite: 'create Instant Invite',
    kickMembers: 'Kick Members',
    banMembers: 'Ban Members',
    administrator: 'Administrator',
    manageChannels: 'Manage Channels',
    manageGuild: 'Manage Guild',
    addReactions: 'Add Reactions',
    readMessages: 'Read Messages',
    sendMessages: 'Send Messages',
    sendTTSMessages: 'Send TTS Messages',
    manageMessages: 'Manage Messages',
    embedLinks: 'Embed Links',
    attachFiles: 'Attach Files',
    readMessageHistory: 'Read Message History',
    mentionEveryone: 'Mention Everyone',
    externalEmojis: 'External Emojis',
    voiceConnect: 'Voice Connect',
    voiceSpeak: 'Voice Speak',
    voiceMuteMembers: 'Voice Mute Members',
    voiceDeafenMembers: 'Voice Deafen Members',
    voiceMoveMembers: 'Voice Move Members',
    voiceUseVAD: 'Voice Use VAD',
    changeNickname: 'Change Nickname',
    manageNicknames: 'Manage Nicknames',
    manageRoles: 'Manage Roles',
    manageWebhooks: 'Manage Webhooks',
    manageEmojis: 'Manage Emojis',
};

const adminPerms = ['administrator', 'manageGuild'];

const typeWH = {
    status: 'Status',
    loader: 'Loader',
    error: 'Error',
    misc: 'Misc',
};

const typeError = {
    api: 'DAPI error - failed to retrieve from Discord',
    db: 'DB error - failed to retrieve from the DB',
    internal: 'Internal error - AxonClient/internal methods',
    unexpected: 'Unexpected error',
};

const permissionNumbers = {
    createInstantInvite: 1,
    kickMembers: 2,
    banMembers: 4,
    administrator: 8,
    manageChannels: 16,
    manageGuild: 32,
    addReactions: 64,
    viewAuditLogs: 128,
    voicePrioritySpeaker: 256,
    readMessages: 1024,
    sendMessages: 2048,
    sendTTSMessages: 4096,
    manageMessages: 8192,
    embedLinks: 16384,
    attachFiles: 32768,
    readMessageHistory: 65536,
    mentionEveryone: 131072,
    externalEmojis: 262144,
    voiceConnect: 1048576,
    voiceSpeak: 2097152,
    voiceMuteMembers: 4194304,
    voiceDeafenMembers: 8388608,
    voiceMoveMembers: 16777216,
    voiceUseVAD: 33554432,
    changeNickname: 67108864,
    manageNicknames: 134217728,
    manageRoles: 268435456,
    manageWebhooks: 536870912,
    manageEmojis: 1073741824,
    all: 2146958847,
    allGuild: 2080374975,
    allText: 805829713,
    allVoice: 871366929,
};


export default {
    permissions,
    permissionsNames,
    adminPerms,
    typeWH,
    typeError,
    nums,
};
